version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "ci:"
    target-branch: "main"
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "build:"
    target-branch: "main"
    groups:
      "com.fasterxml.jackson":
        patterns:
          - "com.fasterxml.jackson*"
